StackName: "gc-guardrails-x"
GitSourceVersion: "1.00"
AWS_REGION: "ca-central-1"
PipelineBucket: ""
EnvironmentName: "esdc-lza-demo"
Parameters:  
  OrganizationName: "ESDC-LZA-Demo"
  OrganizationId: "o-71q12of6wn"
  RootOUID: "r-tn6h"
  AuditAccountID: "343164472410"
  SecurityOUID: "ou-tn6h-t3orw7gj"
  # Can be left default
  RolePrefix: "gc-"
  AccelRolePrefix: "AWSA-"
  AccleratorRole: "OrganizationAccountAccessRole"
  DestBucketName: ""
  EvidenceBucketName: ""
  AWSConfigConformsBucketName: ""
  AdditionalAssessmentAdminRoleARN: ""
  ExecutionName: ""
  DeployRoles: "false"